name: Build LaTeX Document

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Compile LaTeX document
      env:
        TEXINPUTS: "$TEXINPUTS:/project/root"
      run: |
        pdflatex -interaction=nonstopmode -halt-on-error -shell-escape main.tex

    - name: Output PDF file
      uses: actions/upload-artifact@v2
      with:
        name: main.pdf
        path: main.pdf
