name: Build LaTeX Document

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up LaTeX environment
      uses: docker://pandoc/latex

    - name: Compile LaTeX document
      run: |
        pdflatex -interaction=nonstopmode -halt-on-error main.tex

    - name: Output PDF file
      uses: actions/upload-artifact@v2
      with:
        name: main.pdf
        path: main.pdf
